/**
 * @file
 *
 * Standard headers that should be included for all C++ files generated by
 * the compiler.
 */
#pragma once

#include "membirch/external.hpp"
#include "membirch/thread.hpp"
#include "membirch/memory.hpp"
#include "membirch/macro.hpp"
#include "membirch/type.hpp"

#include "membirch/Shared.hpp"
#include "membirch/Any.hpp"
