/**
 * @file
 *
 * Doxygen documentation.
 *
 * @mainpage
 *
 * LibBirch is a compile target for probabilistic programming languages that
 * provides low-level support for the fundamental features that may make up
 * such a language. It includes smart pointers and memory management for lazy
 * deep cloning of objects with copy-on-write. This is particularly important
 * for memory efficiency for universal probabilistic programming languages
 * using Sequential Monte Carlo (SMC) for inference.
 *
 * LibBirch supports C++ code generated by the compiler for Birch
 * (https://birch-lang.org).
 */
