/**
 * @file
 */
#ifdef BACKEND_CUDA
#include "numbirch/cuda/transform.inl"
#endif
#ifdef BACKEND_EIGEN
#include "numbirch/eigen/transform.inl"
#endif
#include "numbirch/common/transform.inl"

#define IBETA(f) \
    IBETA_FIRST(f, real) \
    IBETA_FIRST(f, int) \
    IBETA_FIRST(f, bool)
#define IBETA_FIRST(f, T) \
    IBETA_SECOND(f, T, real) \
    IBETA_SECOND(f, T, int) \
    IBETA_SECOND(f, T, bool)
#define IBETA_SECOND(f, T, U) \
    IBETA_THIRD(f, T, U, real) \
    IBETA_THIRD(f, T, U, int) \
    IBETA_THIRD(f, T, U, bool)
#define IBETA_THIRD(f, T, U, V) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 2), NUMBIRCH_ARRAY(U, 2), NUMBIRCH_ARRAY(V, 2)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 1), NUMBIRCH_ARRAY(U, 1), NUMBIRCH_ARRAY(V, 1)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 0), NUMBIRCH_ARRAY(U, 0), NUMBIRCH_ARRAY(V, 0)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 0), NUMBIRCH_ARRAY(U, 0), V) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 0), U, NUMBIRCH_ARRAY(V, 0)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 0), U, V) \
    IBETA_SIG(f, T, NUMBIRCH_ARRAY(U, 0), NUMBIRCH_ARRAY(V, 0)) \
    IBETA_SIG(f, T, NUMBIRCH_ARRAY(U, 0), V) \
    IBETA_SIG(f, T, U, NUMBIRCH_ARRAY(V, 0)) \
    IBETA_SIG(f, T, U, V) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 2), NUMBIRCH_ARRAY(U, 2), NUMBIRCH_ARRAY(V, 0)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 2), NUMBIRCH_ARRAY(U, 2), V) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 2), NUMBIRCH_ARRAY(U, 0), NUMBIRCH_ARRAY(V, 2)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 2), U, NUMBIRCH_ARRAY(V, 2)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 2), NUMBIRCH_ARRAY(U, 0), NUMBIRCH_ARRAY(V, 0)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 2), NUMBIRCH_ARRAY(U, 0), V) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 2), U, NUMBIRCH_ARRAY(V, 0)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 2), U, V) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 0), NUMBIRCH_ARRAY(U, 2), NUMBIRCH_ARRAY(V, 2)) \
    IBETA_SIG(f, T, NUMBIRCH_ARRAY(U, 2), NUMBIRCH_ARRAY(V, 2)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 0), NUMBIRCH_ARRAY(U, 2), V) \
    IBETA_SIG(f, T, NUMBIRCH_ARRAY(U, 2), NUMBIRCH_ARRAY(V, 0)) \
    IBETA_SIG(f, T, NUMBIRCH_ARRAY(U, 2), V) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 0), NUMBIRCH_ARRAY(U, 0), NUMBIRCH_ARRAY(V, 2)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 0), U, NUMBIRCH_ARRAY(V, 2)) \
    IBETA_SIG(f, T, NUMBIRCH_ARRAY(U, 0), NUMBIRCH_ARRAY(V, 2)) \
    IBETA_SIG(f, T, U, NUMBIRCH_ARRAY(V, 2)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 1), NUMBIRCH_ARRAY(U, 1), NUMBIRCH_ARRAY(V, 0)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 1), NUMBIRCH_ARRAY(U, 1), V) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 1), NUMBIRCH_ARRAY(U, 0), NUMBIRCH_ARRAY(V, 1)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 1), U, NUMBIRCH_ARRAY(V, 1)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 1), NUMBIRCH_ARRAY(U, 0), NUMBIRCH_ARRAY(V, 0)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 1), NUMBIRCH_ARRAY(U, 0), V) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 1), U, NUMBIRCH_ARRAY(V, 0)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 1), U, V) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 0), NUMBIRCH_ARRAY(U, 1), NUMBIRCH_ARRAY(V, 1)) \
    IBETA_SIG(f, T, NUMBIRCH_ARRAY(U, 1), NUMBIRCH_ARRAY(V, 1)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 0), NUMBIRCH_ARRAY(U, 1), NUMBIRCH_ARRAY(V, 0)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 0), NUMBIRCH_ARRAY(U, 1), V) \
    IBETA_SIG(f, T, NUMBIRCH_ARRAY(U, 1), NUMBIRCH_ARRAY(V, 0)) \
    IBETA_SIG(f, T, NUMBIRCH_ARRAY(U, 1), V) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 0), NUMBIRCH_ARRAY(U, 0), NUMBIRCH_ARRAY(V, 1)) \
    IBETA_SIG(f, NUMBIRCH_ARRAY(T, 0), U, NUMBIRCH_ARRAY(V, 1)) \
    IBETA_SIG(f, T, NUMBIRCH_ARRAY(U, 0), NUMBIRCH_ARRAY(V, 1)) \
    IBETA_SIG(f, T, U, NUMBIRCH_ARRAY(V, 1))
#define IBETA_SIG(f, T, U, V) \
    template real_t<T,U,V> f<T,U,V>(const T&, const U&, const V&);

namespace numbirch {
IBETA(ibeta)
}
