env:
  CPPFLAGS: -I/usr/local/include
  LDFLAGS: -L/usr/local/lib
  OMP_NUM_THREADS: 4
  BIRCH_FLAGS: '--unit=unity --jobs=4 --enable-verbose'

task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-14-2
    cpu: 8
    memory: 16G
  install_script:
    - pkg install -y bash m4 autoconf automake libtool elfutils flex bison boost-libs cairo eigen libyaml sqlite3
  birch_build_script:
    - cd birch
    - ./bootstrap
    - ./configure CXXFLAGS="-Wall -Wno-overloaded-virtual" || (cat config.log && exit 1)
    - make -j4
    - sudo make install
    - bash ./smoke.sh
  numbirch_build_script:
    - cd numbirch
    - ./bootstrap
    - ./configure || (cat config.log && exit 1)
    - make -j4
    - sudo make install
  membirch_build_script:
    - cd membirch
    - ./bootstrap
    - ./configure || (cat config.log && exit 1)
    - make -j4
    - sudo make install
  Standard_build_script:
    - cd libraries/Standard
    - birch build ${BIRCH_FLAGS} || (cat config.log && exit 1)
    - sudo make install
  Cairo_build_script:
    - cd libraries/Cairo
    - birch build ${BIRCH_FLAGS} || (cat config.log && exit 1)
    - sudo make install
  SQLite_build_script:
    - cd libraries/SQLite
    - birch build ${BIRCH_FLAGS} || (cat config.log && exit 1)
    - sudo make install
  Test_build_script:
    - cd tests/Test
    - birch build ${BIRCH_FLAGS} || (cat config.log && exit 1)
    - bash ./smoke.sh
  LinearRegression_build_script:
    - cd examples/LinearRegression
    - birch build ${BIRCH_FLAGS} || (cat config.log && exit 1)
    - bash ./smoke.sh
  LinearGaussian_build_script:
    - cd examples/LinearGaussian
    - birch build ${BIRCH_FLAGS} || (cat config.log && exit 1)
    - bash ./smoke.sh
  MixedGaussian_build_script:
    - cd examples/MixedGaussian
    - birch build ${BIRCH_FLAGS} || (cat config.log && exit 1)
    - bash ./smoke.sh
  PoissonGaussian_build_script:
    - cd examples/PoissonGaussian
    - birch build ${BIRCH_FLAGS} || (cat config.log && exit 1)
    - bash ./smoke.sh
  SIR_build_script:
    - cd examples/SIR
    - birch build ${BIRCH_FLAGS} || (cat config.log && exit 1)
    - bash ./smoke.sh
  VectorBorneDisease_build_script:
    - cd examples/VectorBorneDisease
    - birch build ${BIRCH_FLAGS} || (cat config.log && exit 1)
    - bash ./smoke.sh
  MultiObjectTracking_build_script:
    - cd examples/MultiObjectTracking
    - birch build ${BIRCH_FLAGS} || (cat config.log && exit 1)
    - bash ./smoke.sh
  Ecology_build_script:
    - cd examples/Ecology
    - birch build ${BIRCH_FLAGS} || (cat config.log && exit 1)
    - bash ./smoke.sh
