#define LEFT_BRACE                      1
#define RIGHT_BRACE                     2
#define COLON                           3
#define COMMA                           4
#define LEFT_BRACKET                    5
#define RIGHT_BRACKET                   6
#define STRING                          7
#define INT8                            8
#define UINT8                           9
#define INT16                          10
#define INT32                          11
#define INT64                          12
#define FLOAT                          13
#define DOUBLE                         14
#define BOOL                           15
#define NIL                            16
#define NO_OP                          17
