/**
 * @file
 */
#pragma once

#include "bi/statement/Alias.hpp"
#include "bi/statement/Assert.hpp"
#include "bi/statement/AssignmentOperator.hpp"
#include "bi/statement/Assignment.hpp"
#include "bi/statement/Basic.hpp"
#include "bi/statement/BinaryOperator.hpp"
#include "bi/statement/Braces.hpp"
#include "bi/statement/Class.hpp"
#include "bi/statement/ConversionOperator.hpp"
#include "bi/statement/EmptyStatement.hpp"
#include "bi/statement/ExpressionStatement.hpp"
#include "bi/statement/For.hpp"
#include "bi/statement/Fiber.hpp"
#include "bi/statement/Function.hpp"
#include "bi/statement/Generic.hpp"
#include "bi/statement/GlobalVariable.hpp"
#include "bi/statement/If.hpp"
#include "bi/statement/MemberFiber.hpp"
#include "bi/statement/MemberFunction.hpp"
#include "bi/statement/MemberVariable.hpp"
#include "bi/statement/Package.hpp"
#include "bi/statement/Program.hpp"
#include "bi/statement/Raw.hpp"
#include "bi/statement/Return.hpp"
#include "bi/statement/StatementIterator.hpp"
#include "bi/statement/StatementList.hpp"
#include "bi/statement/UnaryOperator.hpp"
#include "bi/statement/While.hpp"
#include "bi/statement/Yield.hpp"
