FROM archlinux:latest
RUN pacman -Syu --noconfirm --needed \
    git \
    openssh \
    tar \
    gzip \
    curl \
    moreutils \
    time \
    ca-certificates \
    binutils \
    elfutils \
    make \
    flex \
    bison \
    gcc \
    lcov \
    gdb \
    autoconf \
    automake \
    libtool \
    jemalloc \
    libyaml \
    boost \
    cairo \
    sqlite \
    eigen \
    && pacman -Sc --noconfirm
