/**
 * @file
 *
 * Standard headers that should be included for all C++ files generated by
 * the compiler.
 */
#pragma once

#include "bi/lib/easy.hpp"
#include "bi/lib/Pointer.hpp"
#include "bi/lib/Coroutine.hpp"

#include <utility>
#include <functional>
#include <string>
#include <cassert>

#include <getopt.h>
#include <gc.h>
