/**
 * @file
 *
 * Standard headers that should be included for all C++ files generated by
 * the compiler.
 */
#pragma once

#include "bi/data/easy.hpp"
#include "bi/exception/MemoryException.hpp"
#include "bi/exception/UnknownOptionException.hpp"

#include <memory>
#include <utility>
#include <functional>
#include <getopt.h>
