
#line 2 "bi/lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[222] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       90,   88,    1,    1,   60,   88,   62,   81,   82,   73,
       71,   78,   72,   85,   74,   50,   50,   79,   75,   65,
       80,   66,   59,   87,   45,   83,   84,   86,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   76,   88,   77,   56,   88,   88,
        4,    3,    8,    7,    8,   12,   11,   12,   16,   15,
       16,   61,   70,    0,   51,    0,   63,   53,   58,    5,
        2,    0,   49,    0,    0,   50,   52,   67,   54,   69,
       68,   45,   45,    0,    0,   45,   45,   45,   45,   45,

       29,   45,   45,   45,   45,   45,   45,   45,   45,   24,
       27,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   13,   64,   55,   45,    6,   10,   14,   51,
        9,   47,    0,   46,   48,   57,   45,   45,   45,   45,
       33,   45,   45,   45,   45,   45,   26,   45,   45,   34,
       42,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,    0,   45,   45,   23,   45,   45,   25,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   35,   43,
       21,   45,   45,    0,   47,   45,   45,   20,   45,   44,
       18,   40,   45,   45,   45,   45,   45,   45,   36,   28,

       32,   45,   30,   45,   45,   37,   45,   45,   45,   31,
       45,   39,   45,   45,   45,   19,   41,   17,   22,   38,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   26,   26,   26,   27,   26,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   29,   28,   28,
       30,   31,   32,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   28,   28,   43,   44,   45,
       46,   47,   28,   48,   49,   50,   51,   28,   52,   29,
       53,   28,   54,   55,   56,   57,    1,   58,   59,    1,
       60,   61,   62,   63,   64,   65,   66,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   67,   68,    1,    1,
        1,   69,    1,    1,   70,    1,    1,   71,    1,   72,
        1,    1,   73,    1,   74,   75,    1,   76,   77,    1,
        1,    1,    1,    1,    1,    1,   78,   79,   80,   81,
       82,   83,   84,   85,   86,   87,   88,   89,   90,   91,
       92,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,   93,   94,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[95] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3

    } ;

static const flex_int16_t yy_base[228] =
    {   0,
        0,    0,  228,  226,   92,   93,   94,   95,   96,   97,
      227,  858,  858,  858,   96,   96,  210,  858,  858,  858,
      858,  858,  180,  182,   96,   93,   98,  858,  858,  107,
      171,  169,  858,  858,  101,  858,  858,  858,  106,  111,
      115,  120,   98,   99,  124,  121,  127,  130,  167,  147,
      139,  171,   98,  184,  135,  132,  858,  157,  171,  206,
      858,  858,  858,  858,  129,  858,  858,  127,  858,  858,
       79,  858,  858,  161,  858,  180,  858,  858,  858,  119,
      858,  120,  258,  216,  263,  276,  102,  858,  858,  858,
      858,  116,  263,  250,  285,  172,  257,  317,  320,  323,

      324,  341,  328,  345,  346,  312,  357,  358,  360,  368,
      371,  374,  382,  384,  385,  393,  401,  403,  401,  412,
      418,  427,  858,  858,  858,  422,  858,  858,  858,  204,
      858,  457,  166,  260,  462,  858,  442,  467,  468,  455,
      459,  477,  485,  478,  486,  496,  490,  497,  503,  507,
      508,  512,  521,  523,  526,  532,  531,  549,  550,  543,
      554,  270,  554,  563,  565,  561,  573,  574,  591,  579,
      590,  596,  600,  611,  613,  609,  610,  619,  627,  628,
      629,  645,  637,  292,  295,  653,  647,  643,  661,  651,
      664,  667,  677,  680,  681,  694,  698,  695,  697,  708,

      711,  717,  714,  727,  725,  728,  731,  744,  742,  746,
      748,  752,  761,  762,  770,  771,  779,  780,  781,  789,
      858,  842,  845,  848,  851,  854,  114
    } ;

static const flex_int16_t yy_def[228] =
    {   0,
      221,    1,  222,  222,  223,  223,  224,  224,  225,  225,
      221,  221,  221,  221,  221,  226,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  227,  221,  221,  221,  227,  227,
      227,  227,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   52,   52,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  226,  221,  226,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,   52,  221,  221,   39,   39,   39,   39,   39,

       39,   39,   39,   39,   39,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   39,   39,
       39,   39,  221,  221,  221,   39,  221,  221,  221,  226,
      221,  221,  221,  221,  221,  221,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   52,   52,   52,   39,   39,   39,   39,   39,   39,
       39,  221,   52,   52,   52,   39,   39,   39,   39,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,  221,  221,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,

       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
        0,  221,  221,  221,  221,  221,  221
    } ;

static const flex_int16_t yy_nxt[953] =
    {   0,
       12,   13,   14,   13,   15,   16,   17,   12,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   35,   35,   35,   36,
       12,   37,   38,   39,   35,   40,   41,   42,   43,   44,
       45,   46,   35,   35,   47,   48,   49,   50,   51,   52,
       35,   53,   54,   55,   56,   57,   58,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   59,   60,   64,   64,   67,   67,   70,   70,

       72,   75,   65,   65,   68,   68,   80,   82,   92,   83,
       83,   81,   82,   92,   86,   86,   93,   73,   92,   84,
       87,   85,   92,   92,   84,  136,   76,   92,   88,  131,
       84,  104,   93,   93,  129,   84,  132,  132,  121,  105,
       96,  108,  128,  106,  127,   93,   93,   93,  107,   93,
       93,   71,   71,   99,   97,   93,   98,  100,   93,  110,
      101,   93,  103,   89,   93,  111,   75,  102,  112,   93,
      109,   93,   93,   93,   93,   93,  113,   93,   93,  125,
       93,   93,  134,  134,  116,  130,  124,   93,  123,  117,
       91,   76,   90,   94,   95,   93,   79,   93,   94,   95,

      114,   93,   78,   94,   95,   93,   93,   94,   95,   75,
       76,  118,   94,   95,  115,   93,   77,   93,  119,   93,
      137,   93,   93,  120,   93,  122,  221,  133,   62,  133,
       62,   93,  134,  134,   76,  221,   93,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,  126,   82,  221,   83,   83,  134,  134,  221,  135,
      135,  184,  221,  184,   84,  221,  185,  185,  135,  135,
       82,   93,   86,   86,  221,   84,  135,  135,  135,  135,

      135,  135,   84,   93,  221,  138,  221,   93,  185,  185,
       93,  185,  185,   84,  221,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,  140,   93,  221,  221,   93,   93,  147,
      221,  221,   93,  221,   93,   93,  139,   93,   93,  141,
       93,   93,   93,   93,   93,   93,  143,  221,   93,   93,
      145,  221,  221,  221,  221,  142,  221,  144,  221,   93,
      146,   93,  221,   93,   93,   93,   93,   93,   93,  221,

       93,  148,  221,  149,   93,   93,  150,   93,   93,   93,
       93,   93,   93,  221,   93,   93,  151,  221,   93,  152,
       93,   93,   93,   93,   93,   93,   93,  221,  221,   93,
      154,  153,   93,   93,   93,   93,   93,   93,  221,  221,
       93,   93,  155,   93,  157,   93,   93,  156,   93,   93,
       93,  158,   93,   93,  221,   93,   93,  221,  159,  160,
       93,   93,   93,  221,  161,  221,   93,  221,   93,  221,
       93,  221,   93,  132,  132,   93,   93,   93,  135,  135,
      221,  221,  221,  162,  221,  221,  221,  135,  135,   93,
       93,  163,   93,   93,  162,  135,  135,  135,  135,  135,

      135,   93,   93,  166,  164,   93,  221,   93,  221,   93,
      167,   93,   93,  165,  221,   93,   93,   93,   93,   93,
       93,  221,  168,  170,   93,   93,  169,   93,   93,  171,
       93,   93,  172,   93,   93,   93,   93,  173,   93,  221,
       93,   93,   93,  221,   93,   93,   93,   93,  221,  221,
      221,   93,   93,   93,  175,   93,   93,   93,   93,  174,
       93,   93,  176,   93,   93,   93,   93,  221,   93,  178,
       93,  221,  221,   93,   93,   93,  177,   93,  221,  179,
       93,   93,   93,   93,   93,  182,  180,  181,   93,  221,
      221,   93,  221,   93,   93,   93,  183,   93,   93,   93,

       93,  186,   93,   93,   93,   93,   93,   93,   93,  188,
      187,   93,   93,  221,  221,   93,  189,   93,  221,   93,
      221,   93,   93,   93,   93,   93,  191,  221,  190,  221,
       93,   93,  192,  194,  221,  221,   93,   93,  221,   93,
       93,   93,   93,   93,  195,  193,  221,   93,   93,   93,
       93,   93,   93,   93,  221,  196,  197,  198,   93,   93,
       93,   93,   93,   93,  221,   93,  199,   93,   93,   93,
      221,   93,  221,  201,   93,   93,   93,   93,  221,   93,
       93,   93,  200,   93,   93,   93,  202,   93,  221,   93,
       93,   93,   93,   93,   93,   93,  203,   93,   93,   93,

       93,   93,  204,   93,   93,   93,  221,   93,   93,  221,
      221,   93,  221,   93,   93,  221,   93,   93,  205,   93,
       93,   93,  206,  221,   93,  221,  221,   93,   93,   93,
      207,  209,   93,   93,   93,   93,  208,   93,   93,  210,
      221,   93,   93,  221,   93,   93,   93,   93,   93,   93,
       93,   93,  211,  221,   93,   93,  221,   93,   93,  221,
       93,   93,  212,   93,   93,   93,   93,   93,   93,   93,
      213,   93,   93,  221,   93,   93,  214,   93,   93,   93,
       93,  215,   93,   93,   93,  216,   93,  221,   93,   93,
      221,   93,   93,   93,   93,   93,   93,  217,   93,   93,

       93,   93,   93,  221,   93,  218,  221,  221,   93,  219,
       93,   93,  220,   93,   93,  221,  221,   93,   93,   93,
       93,   93,   93,   93,  221,  221,   93,   93,   93,   93,
      221,   93,   93,   93,  221,  221,   93,  221,  221,  221,
      221,   93,   61,   61,   61,   63,   63,   63,   66,   66,
       66,   69,   69,   69,   74,  221,   74,   11,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,

      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221
    } ;

static const flex_int16_t yy_chk[953] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    6,    7,    8,    9,   10,

       15,   16,    5,    6,    7,    8,   25,   26,   35,   26,
       26,   25,   27,   39,   27,   27,  227,   15,   40,   26,
       30,   26,   41,   92,   27,   87,   16,   42,   30,   80,
       26,   43,   43,   44,   71,   27,   82,   82,   53,   43,
       39,   44,   68,   43,   65,   53,   43,   44,   43,   44,
       53,    9,   10,   40,   39,   46,   39,   40,   45,   46,
       41,   47,   42,   30,   48,   46,   74,   41,   47,   46,
       45,   46,   45,   51,   45,   47,   48,   47,   48,   58,
       48,   50,  133,  133,   50,   76,   56,   51,   55,   51,
       32,   74,   31,   35,   35,   50,   24,   50,   39,   39,

       49,   49,   23,   40,   40,   52,   96,   41,   41,  130,
       76,   52,   42,   42,   49,   49,   17,   49,   52,   52,
       96,   52,   96,   52,   54,   54,   11,   84,    4,   84,
        3,   54,   84,   84,  130,    0,   54,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   83,    0,   83,   83,  134,  134,    0,   85,
       85,  162,    0,  162,   83,    0,  162,  162,   85,   85,
       86,   97,   86,   86,    0,   83,   85,   85,   85,   85,

       85,   85,   86,   93,    0,   97,    0,   97,  184,  184,
       93,  185,  185,   86,    0,   93,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   98,  106,   99,   99,    0,    0,  100,  101,  106,
        0,    0,  103,    0,  106,   98,   98,   98,   99,  100,
       99,  100,  101,  100,  101,  102,  103,    0,  103,  104,
      105,    0,    0,    0,    0,  102,    0,  104,    0,  102,
      105,  102,    0,  104,  105,  104,  105,  107,  108,    0,

      109,  107,    0,  108,  107,  108,  109,  109,  110,  107,
      108,  111,  109,    0,  112,  110,  112,    0,  111,  113,
      110,  112,  113,  111,  114,  115,  112,    0,    0,  113,
      115,  114,  115,  116,  113,  119,  114,  115,    0,    0,
      116,  117,  116,  118,  118,  116,  120,  117,  117,  119,
      118,  119,  121,  117,    0,  118,  126,    0,  120,  121,
      120,  122,  120,    0,  122,    0,  121,    0,  121,    0,
      126,    0,  126,  132,  132,  122,  137,  122,  135,  135,
        0,    0,    0,  132,    0,    0,    0,  135,  135,  140,
      137,  137,  137,  141,  132,  135,  135,  135,  135,  135,

      135,  138,  139,  140,  138,  140,    0,  141,    0,  141,
      142,  142,  144,  139,    0,  138,  139,  138,  139,  143,
      145,    0,  143,  145,  147,  142,  144,  142,  144,  146,
      146,  148,  148,  143,  145,  143,  145,  149,  147,    0,
      147,  150,  151,    0,  146,  148,  146,  148,    0,    0,
        0,  149,  152,  149,  153,  150,  151,  150,  151,  152,
      155,  153,  154,  154,  152,  157,  156,    0,  153,  156,
      154,    0,    0,  153,  155,  154,  155,  160,    0,  157,
      156,  157,  156,  158,  159,  160,  158,  159,  161,    0,
        0,  160,    0,  160,  163,  166,  161,  158,  159,  158,

      159,  163,  161,  164,  161,  165,  163,  167,  168,  166,
      164,  166,  165,    0,    0,  164,  167,  165,    0,  170,
        0,  167,  168,  167,  168,  169,  170,    0,  169,    0,
      171,  170,  171,  173,    0,    0,  172,  171,    0,  169,
      173,  169,  171,  172,  174,  172,    0,  173,  172,  176,
      177,  174,  173,  175,    0,  175,  176,  177,  174,  178,
      175,  176,  177,  174,    0,  175,  178,  179,  180,  181,
        0,  178,    0,  183,  179,  180,  181,  183,    0,  179,
      180,  181,  182,  188,  183,  182,  186,  187,    0,  183,
      188,  190,  182,  186,  187,  188,  187,  182,  190,  187,

      186,  189,  189,  190,  191,  186,    0,  192,  189,    0,
        0,  191,    0,  189,  192,    0,  191,  193,  193,  192,
      194,  195,  194,    0,  193,    0,    0,  194,  195,  193,
      195,  197,  194,  195,  196,  198,  196,  199,  197,  198,
        0,  196,  198,    0,  199,  197,  196,  198,  200,  199,
      197,  201,  202,    0,  203,  200,    0,  202,  201,    0,
      200,  203,  204,  201,  202,  205,  203,  204,  206,  202,
      205,  207,  205,    0,  204,  206,  207,  205,  207,  204,
      206,  208,  209,  207,  208,  209,  210,    0,  211,  209,
        0,  208,  212,  210,  209,  211,  208,  211,  210,  212,

      211,  213,  214,    0,  212,  213,    0,    0,  213,  214,
      215,  216,  215,  213,  214,    0,    0,  215,  216,  217,
      218,  219,  215,  216,    0,    0,  217,  218,  219,  220,
        0,  217,  218,  219,    0,    0,  220,    0,    0,    0,
        0,  220,  222,  222,  222,  223,  223,  223,  224,  224,
      224,  225,  225,  225,  226,    0,  226,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,

      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "bi/lexer.lpp"
#line 2 "bi/lexer.lpp"
#include "parser.hpp"
#include "lexer.hpp"
#include "build/Compiler.hpp"

/* Flex uses the register keyword, this is deprecated in C++11, and removed
 * in C++17, so define it away */
#define register

#define YY_USER_ACTION yycount();

extern bi::Compiler* compiler;
int yyline = 1, yycol = 1;

void yyerror(const char *msg) {
  yylocation();
  std::cerr << msg << '\n';
  exit(-1);
}

void yywarn(const char *msg) {
  yylocation();
  std::cerr << "warning: " << msg << '\n';
}

void yylocation() {
  /* the format here matches that of g++ and clang++ such that Eclipse,
   * when parsing the error output, is able to annotate lines within the
   * editor */
  if (compiler->file) {
    std::cerr << compiler->file->path;
    std::cerr << ':' << yylloc.first_line;
    std::cerr << ':' << yylloc.first_column;
    std::cerr << ": ";
  }
}

void yycount() {
  yylloc.first_line = yyline;
  yylloc.first_column = yycol;

  for (int i = 0; yytext[i] != '\0'; ++i) {
    if (yytext[i] == '\n') {
      ++yyline;
      yycol = 1;
    } else if (yytext[i] == '\t') {
      yycol += 8 - (yycol % 8);
    } else {
      ++yycol;
    }
  }

  yylloc.last_line = yyline;
  yylloc.last_column = yycol;
}

void yyreset() {
  yyline = 1;
  yycol = 1;
}

#line 794 "bi/lexer.cpp"
#define YY_NO_INPUT 1

#line 797 "bi/lexer.cpp"

#define INITIAL 0
#define COMMENT_EOL 1
#define COMMENT_INLINE 2
#define COMMENT_DOC 3
#define DOUBLE_BRACE 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 75 "bi/lexer.lpp"


#line 1019 "bi/lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 222 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 858 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 77 "bi/lexer.lpp"

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 79 "bi/lexer.lpp"
{ BEGIN(COMMENT_EOL); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 80 "bi/lexer.lpp"
{ BEGIN(INITIAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 81 "bi/lexer.lpp"
{ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 83 "bi/lexer.lpp"
{ BEGIN(COMMENT_INLINE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 84 "bi/lexer.lpp"
{ BEGIN(INITIAL); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 85 "bi/lexer.lpp"
{ }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 86 "bi/lexer.lpp"
{ }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 88 "bi/lexer.lpp"
{ BEGIN(COMMENT_DOC); raw.str(""); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 89 "bi/lexer.lpp"
{ BEGIN(INITIAL); }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 90 "bi/lexer.lpp"
{ raw << yytext; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 91 "bi/lexer.lpp"
{ raw << yytext; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 93 "bi/lexer.lpp"
{ BEGIN(DOUBLE_BRACE); raw.str(""); return DOUBLE_BRACE_OPEN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 94 "bi/lexer.lpp"
{ BEGIN(INITIAL); return DOUBLE_BRACE_CLOSE; }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 95 "bi/lexer.lpp"
{ raw << yytext; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 96 "bi/lexer.lpp"
{ raw << yytext; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 98 "bi/lexer.lpp"
{ return FUNCTION; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 99 "bi/lexer.lpp"
{ return FIBER; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 100 "bi/lexer.lpp"
{ return PROGRAM; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 101 "bi/lexer.lpp"
{ return CLASS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 102 "bi/lexer.lpp"
{ return TYPE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 103 "bi/lexer.lpp"
{ return OPERATOR; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 104 "bi/lexer.lpp"
{ return AUTO; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 105 "bi/lexer.lpp"
{ return IF; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 106 "bi/lexer.lpp"
{ return ELSE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 107 "bi/lexer.lpp"
{ return FOR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 108 "bi/lexer.lpp"
{ return IN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 109 "bi/lexer.lpp"
{ return WHILE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 110 "bi/lexer.lpp"
{ return DO; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 111 "bi/lexer.lpp"
{ return ASSERT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 112 "bi/lexer.lpp"
{ return RETURN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 113 "bi/lexer.lpp"
{ return YIELD; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 114 "bi/lexer.lpp"
{ return CPP; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 115 "bi/lexer.lpp"
{ return HPP; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 116 "bi/lexer.lpp"
{ return THIS; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 117 "bi/lexer.lpp"
{ return SUPER; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 118 "bi/lexer.lpp"
{ return GLOBAL; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 119 "bi/lexer.lpp"
{ return PARALLEL; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 120 "bi/lexer.lpp"
{ return DYNAMIC; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 121 "bi/lexer.lpp"
{ return FINAL; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 122 "bi/lexer.lpp"
{ return ABSTRACT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 123 "bi/lexer.lpp"
{ return NIL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 125 "bi/lexer.lpp"
{ yylval.valString = "true"; return BOOL_LITERAL; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 126 "bi/lexer.lpp"
{ yylval.valString = "false"; return BOOL_LITERAL; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 128 "bi/lexer.lpp"
{ yylval.valString = strdup(yytext); return NAME; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 130 "bi/lexer.lpp"
{ yylval.valString = strdup(yytext); return REAL_LITERAL; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 131 "bi/lexer.lpp"
{ yylval.valString = strdup(yytext); return REAL_LITERAL; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 132 "bi/lexer.lpp"
{ yylval.valString = strdup(yytext); return INT_LITERAL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 133 "bi/lexer.lpp"
{ yylval.valString = strdup(yytext); return INT_LITERAL; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 134 "bi/lexer.lpp"
{ yylval.valString = strdup(yytext); return INT_LITERAL; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 135 "bi/lexer.lpp"
{ yylval.valString = strdup(yytext); return STRING_LITERAL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 137 "bi/lexer.lpp"
{ return LEFT_OP; } 
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 138 "bi/lexer.lpp"
{ return RIGHT_OP; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 139 "bi/lexer.lpp"
{ return LEFT_TILDE_OP; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 140 "bi/lexer.lpp"
{ return RIGHT_TILDE_OP; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 141 "bi/lexer.lpp"
{ return '~'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 142 "bi/lexer.lpp"
{ return LEFT_QUERY_OP; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 143 "bi/lexer.lpp"
{ return RANGE_OP; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 144 "bi/lexer.lpp"
{ return '?'; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 145 "bi/lexer.lpp"
{ return '!'; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 146 "bi/lexer.lpp"
{ return SPIN_OP; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 147 "bi/lexer.lpp"
{ return '&'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 148 "bi/lexer.lpp"
{ return AND_OP; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 149 "bi/lexer.lpp"
{ return OR_OP; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 150 "bi/lexer.lpp"
{ return '<'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 151 "bi/lexer.lpp"
{ return '>'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 152 "bi/lexer.lpp"
{ return LE_OP; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 153 "bi/lexer.lpp"
{ return GE_OP; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 154 "bi/lexer.lpp"
{ return EQ_OP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 155 "bi/lexer.lpp"
{ return NE_OP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 156 "bi/lexer.lpp"
{ return '+'; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 157 "bi/lexer.lpp"
{ return '-'; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 158 "bi/lexer.lpp"
{ return '*'; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 159 "bi/lexer.lpp"
{ return '/'; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 160 "bi/lexer.lpp"
{ return ';'; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 161 "bi/lexer.lpp"
{ return '{'; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 162 "bi/lexer.lpp"
{ return '}'; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 163 "bi/lexer.lpp"
{ return ','; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 164 "bi/lexer.lpp"
{ return ':'; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 165 "bi/lexer.lpp"
{ return '='; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 166 "bi/lexer.lpp"
{ return '('; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 167 "bi/lexer.lpp"
{ return ')'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 168 "bi/lexer.lpp"
{ return '['; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 169 "bi/lexer.lpp"
{ return ']'; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 170 "bi/lexer.lpp"
{ return '.'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 171 "bi/lexer.lpp"
{ return '_'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 172 "bi/lexer.lpp"
{ return '@'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 173 "bi/lexer.lpp"
{ yyerror("syntax error"); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 175 "bi/lexer.lpp"
ECHO;
	YY_BREAK
#line 1526 "bi/lexer.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT_EOL):
case YY_STATE_EOF(COMMENT_INLINE):
case YY_STATE_EOF(COMMENT_DOC):
case YY_STATE_EOF(DOUBLE_BRACE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 222 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 222 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 221);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 175 "bi/lexer.lpp"


