FROM alpine:3.12.0
RUN apk update && apk add --no-cache \
    git \
    openssh \
    tar \
    gzip \
    ca-certificates \
    g++ \
    make \
    autoconf \
    automake \
    flex \
    bison \
    libtool \
    eigen-dev \
    yaml-dev \
    boost-dev \
    sqlite-dev \
    cairo-dev
