all:
	birch build --verbose --enable-warnings

install:
	birch install --verbose --enable-warnings

uninstall:
	birch uninstall --verbose --enable-warnings

clean:
	rm -rf build autom4te.cache autogen.sh common.am configure.ac Makefile.am configure
