/**
 * @file
 */
#pragma once

#include "src/statement/Assert.hpp"
#include "src/statement/AssignmentOperator.hpp"
#include "src/statement/Basic.hpp"
#include "src/statement/BinaryOperator.hpp"
#include "src/statement/Block.hpp"
#include "src/statement/Braces.hpp"
#include "src/statement/Class.hpp"
#include "src/statement/ConversionOperator.hpp"
#include "src/statement/DoWhile.hpp"
#include "src/statement/EmptyStatement.hpp"
#include "src/statement/ExpressionStatement.hpp"
#include "src/statement/Factor.hpp"
#include "src/statement/For.hpp"
#include "src/statement/Function.hpp"
#include "src/statement/GlobalVariable.hpp"
#include "src/statement/If.hpp"
#include "src/statement/LocalVariable.hpp"
#include "src/statement/MemberFunction.hpp"
#include "src/statement/MemberVariable.hpp"
#include "src/statement/Package.hpp"
#include "src/statement/Parallel.hpp"
#include "src/statement/Program.hpp"
#include "src/statement/Raw.hpp"
#include "src/statement/Return.hpp"
#include "src/statement/SliceOperator.hpp"
#include "src/statement/StatementIterator.hpp"
#include "src/statement/StatementList.hpp"
#include "src/statement/UnaryOperator.hpp"
#include "src/statement/While.hpp"
#include "src/statement/With.hpp"
